# Projet Machine learning 

## Valeurs foncières

### Traitement des données. 

Les données ont été téléchargées depuis le site des demandes de valeurs foncières du gouvernement : [DVF](https://www.data.gouv.fr/fr/datasets/demandes-de-valeurs-foncieres/).

Nous nous concentrerons tous d'abord sur l'année 2023 afin de développer / entrainer nos différents modèles puis observerons leur justesse sur les autres années

#### Chargement des données

Les données étant initialement téléchargées sont sous format `txt`, nous devons convertir le format de fichier en `.csv`.

Ensuite, nous pouvons créer un DataFrame pandas pour manipuler les données.

In [75]:
import pandas as pd
import numpy as np

In [76]:

data_path = "../data/valeursfoncieres-2023.csv"
data = pd.read_csv(data_path, sep="|", decimal=",")

/var/folders/fk/l7l7wjhd4rv76ggs6x5wt45m0000gn/T/ipykernel_43831/3927644805.py:2: DtypeWarning: Columns (14,18,23,24,26,28,32,41) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(data_path, sep="|", decimal=",")

#### Examination préliminaire

Nous jetons un premier coup d'oeil aux données

In [77]:
data.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3727005 entries, 0 to 3727004
Data columns (total 43 columns):
 #   Column                      Dtype
---  ------                      -----
 0   Identifiant de document     float64
 1   Reference document          float64
 2   1 Articles CGI              float64
 3   2 Articles CGI              float64
 4   3 Articles CGI              float64
 5   4 Articles CGI              float64
 6   5 Articles CGI              float64
 7   No disposition              int64
 8   Date mutation               object
 9   Nature mutation             object
 10  Valeur fonciere             float64
 11  No voie                     float64
 12  B/T/Q                       object
 13  Type de voie                object
 14  Code voie                   object
 15  Voie                        object
 16  Code postal                 float64
 17  Commune                     object
 18  Code departement            object
 19  Code commune                int64
 20  Prefixe de section          float64
 21  Section                     object
 22  No plan                     int64
 23  No Volume                   object
 24  1er lot                     object
 25  Surface Carrez du 1er lot   float64
 26  2eme lot                    object
 27  Surface Carrez du 2eme lot  float64
 28  3eme lot                    object
 29  Surface Carrez du 3eme lot  float64
 30  4eme lot                    float64
 31  Surface Carrez du 4eme lot  float64
 32  5eme lot                    object
 33  Surface Carrez du 5eme lot  float64
 34  Nombre de lots              int64
 35  Code type local             float64
 36  Type local                  object
 37  Identifiant local           float64
 38  Surface reelle bati         float64
 39  Nombre pieces principales   float64
 40  Nature culture              object
 41  Nature culture speciale     object
 42  Surface terrain             float64
dtypes: float64(22), int64(4), object(17)
memory usage: 1.2+ GB

In [78]:
data.head()

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,05/01/2023,Vente,1070000.0,184.0,NaN,ALL,0124,DES HETRES,1630.0,ST-GENIS-POUILLY,1,354,NaN,BD,334,NaN,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3.0,Dépendance,NaN,0.0,0.0,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,05/01/2023,Vente,1070000.0,159.0,NaN,ALL,0124,DES HETRES,1630.0,ST-GENIS-POUILLY,1,354,NaN,BD,336,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3.0,Dépendance,NaN,0.0,0.0,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,05/01/2023,Vente,1070000.0,159.0,NaN,ALL,0124,DES HETRES,1630.0,ST-GENIS-POUILLY,1,354,NaN,BD,336,NaN,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,233.0,8.0,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,03/01/2023,Vente,152200.0,2914.0,NaN,RTE,0107,DE PONCIN,1450.0,SERRIERES-SUR-AIN,1,404,NaN,D,2317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,64.0,3.0,S,NaN,988.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,05/01/2023,Vente,269000.0,427.0,T,CHE,0040,DE L'AUBEPIN,1800.0,SAINT-JEAN-DE-NIOST,1,361,NaN,B,2405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,73.0,3.0,S,NaN,835.0

In [79]:
data.describe()

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Valeur fonciere,No voie,Code postal,Code commune,Prefixe de section,No plan,Surface Carrez du 1er lot,Surface Carrez du 2eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Surface terrain
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.727005e+06,3.694626e+06,2.311358e+06,3.698497e+06,3.727005e+06,172197.000000,3.727005e+06,330096.000000,108657.000000,12171.000000,19977.000000,2829.000000,921.000000,3.727005e+06,2.142541e+06,0.0,2.140070e+06,2.140070e+06,2.556488e+06
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.079793e+00,6.164600e+05,6.987214e+02,4.977735e+04,2.055213e+02,437.892309,4.099085e+02,66.462640,63.625383,69.102282,137.004655,82.794846,98.902845,4.356270e-01,2.274490e+00,NaN,6.426647e+01,1.732375e+00,2.992813e+03
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.119859e+00,5.152410e+06,2.006985e+03,2.751929e+04,1.657777e+02,315.715101,5.769833e+02,174.512852,82.702430,91.442594,2642.633860,96.645657,120.118130,8.497163e-01,9.243697e-01,NaN,5.343657e+02,2.058939e+00,1.273271e+04
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00,1.000000e-01,1.000000e+00,1.000000e+03,1.000000e+00,1.000000,1.000000e+00,0.200000,0.100000,0.430000,2.000000,0.800000,0.870000,0.000000e+00,1.000000e+00,NaN,0.000000e+00,0.000000e+00,0.000000e+00
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00,6.200000e+04,8.000000e+00,2.765000e+04,7.400000e+01,164.000000,8.300000e+01,35.240000,43.380000,41.580000,7.000000,39.350000,38.400000,0.000000e+00,1.000000e+00,NaN,0.000000e+00,0.000000e+00,2.520000e+02
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00,1.606000e+05,2.400000e+01,4.860000e+04,1.690000e+02,320.000000,2.200000e+02,54.410000,61.050000,61.100000,20.000000,67.480000,73.730000,0.000000e+00,2.000000e+00,NaN,3.000000e+01,1.000000e+00,6.410000e+02
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00,3.039000e+05,9.700000e+01,7.500700e+04,2.920000e+02,820.000000,5.030000e+02,73.310000,75.960000,82.630000,55.000000,98.240000,113.490000,1.000000e+00,3.000000e+00,NaN,8.000000e+01,3.000000e+00,1.930000e+03
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.940000e+02,7.620000e+08,9.999000e+03,9.749000e+04,9.090000e+02,950.000000,9.914000e+03,9042.000000,8020.000000,5505.000000,201411.000000,2494.000000,2006.900000,1.500000e+02,4.000000e+00,NaN,1.995470e+05,9.500000e+01,4.653206e+06

### Quelles données sont absentes ?

On peut voir que certaines colonnes sont entièrement vides, nous pouvons donc les supprimer

In [80]:
nan_count = data.isna().sum()
cols_to_drop = []
for i in range(len(nan_count)):
	if nan_count.values[i] == 3727005:
		#print(nan_count.index[i])
		cols_to_drop.append(nan_count.index[i])
print(cols_to_drop)

['Identifiant de document', 'Reference document', '1 Articles CGI', '2 Articles CGI', '3 Articles CGI', '4 Articles CGI', '5 Articles CGI', 'Identifiant local']

In [81]:
data = data.drop(labels=cols_to_drop, axis=1)

In [84]:
#print(data)
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3727005 entries, 0 to 3727004
Data columns (total 35 columns):
 #   Column                      Dtype
---  ------                      -----
 0   No disposition              int64
 1   Date mutation               object
 2   Nature mutation             object
 3   Valeur fonciere             float64
 4   No voie                     float64
 5   B/T/Q                       object
 6   Type de voie                object
 7   Code voie                   object
 8   Voie                        object
 9   Code postal                 float64
 10  Commune                     object
 11  Code departement            object
 12  Code commune                int64
 13  Prefixe de section          float64
 14  Section                     object
 15  No plan                     int64
 16  No Volume                   object
 17  1er lot                     object
 18  Surface Carrez du 1er lot   float64
 19  2eme lot                    object
 20  Surface Carrez du 2eme lot  float64
 21  3eme lot                    object
 22  Surface Carrez du 3eme lot  float64
 23  4eme lot                    float64
 24  Surface Carrez du 4eme lot  float64
 25  5eme lot                    object
 26  Surface Carrez du 5eme lot  float64
 27  Nombre de lots              int64
 28  Code type local             float64
 29  Type local                  object
 30  Surface reelle bati         float64
 31  Nombre pieces principales   float64
 32  Nature culture              object
 33  Nature culture speciale     object
 34  Surface terrain             float64
dtypes: float64(14), int64(4), object(17)
memory usage: 995.2+ MB
None

### Enlever les valeurs inutiles

In [85]:
print(data.columns)

Index(['No disposition', 'Date mutation', 'Nature mutation', 'Valeur fonciere',
       'No voie', 'B/T/Q', 'Type de voie', 'Code voie', 'Voie', 'Code postal',
       'Commune', 'Code departement', 'Code commune', 'Prefixe de section',
       'Section', 'No plan', 'No Volume', '1er lot',
       'Surface Carrez du 1er lot', '2eme lot', 'Surface Carrez du 2eme lot',
       '3eme lot', 'Surface Carrez du 3eme lot', '4eme lot',
       'Surface Carrez du 4eme lot', '5eme lot', 'Surface Carrez du 5eme lot',
       'Nombre de lots', 'Code type local', 'Type local',
       'Surface reelle bati', 'Nombre pieces principales', 'Nature culture',
       'Nature culture speciale', 'Surface terrain'],
      dtype='object')

On suppose que ces colonnes n'ont aucun impact :
- No voie
- Code voie (répétition de Type de voie mais en entiers)
- Code type local (répétition de Type de local mais en entiers)
- Prefixe de session
- Section
- No Plan

In [86]:
labels_to_drop = ["No voie", "Code voie", "Code type local", "Prefixe de section", "Section", "No plan"]
data = data.drop(labels=labels_to_drop, axis=1)

### Removing duplicates

In [87]:
data = data[data.duplicated(keep=False)]